### ISSUE TITLE
cannot import in Electron

### ISSUE THREAD

**Issue by Fauny** [cmake-js/fastcall#35]
### env:
*Windows 10, x64
*Node v8.11.3
*Yarn v1.7.0
*Electron v2.0..4 & v2.0.1

### nothing but import
```import fastcall from 'fastcall'```
### got error，in both main and renderer process
```
Error: Module did not self-register.
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
      at Object.Module._extensions..node (module.js:671:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at bindings (<project-root>\node_modules\bindings\bindings.js:81:44)
      at Object.<anonymous> (<project-root>\node_modules\fastcall\lib\ref-libs\ref.js:5:47)
```
i'v tried rebuild it in node_modules/fastcall path, the error still.

**Comment by Fauny** [comment]
i'v found the solution:
https://github.com/chentsulin/electron-react-boilerplate/issues/646#issuecomment-270685328
